import {
  PolicyPageShell,
  PolicySection,
  PolicyP,
  PolicyOl,
  PolicyUl,
  PolicyNote,
  POLICY_BUSINESS,
  POLICY_SITE,
  POLICY_ADDRESS,
} from '@/lib/policies';

export function TermsPage() {
  return (
    <PolicyPageShell
      eyebrow="Legal"
      title="Terms & Conditions"
      intro={
        <>
          These Terms & Conditions govern your use of the website{' '}
          <span className="text-bone">{POLICY_SITE}</span> and the placement of orders with{' '}
          <span className="text-bone">{POLICY_BUSINESS}</span>. By accessing the website or
          placing an order, you agree to be bound by these terms.
        </>
      }
    >
      <PolicySection num={1} title="Electronic Record Notice">
        <PolicyP>
          This document is an electronic record in terms of the Information Technology Act, 2000 and
          the rules made thereunder. It is generated by a computer system and does not require any
          physical or digital signature.
        </PolicyP>
      </PolicySection>

      <PolicySection num={2} title="Website & Platform Usage">
        <PolicyP>
          The website {POLICY_SITE} is operated by {POLICY_BUSINESS} to display and sell clothing
          products directly to customers. The site provides product information, live stock
          availability and an ordering interface. You may use the website only for lawful purposes,
          and you agree not to attempt to gain unauthorised access to any part of the website, its
          servers or related systems.
        </PolicyP>
        <PolicyP>
          We work to keep product descriptions, sizing and availability accurate, but we do not
          guarantee that every description, image or price is free of error. We reserve the right to
          correct any pricing or specification error and to refuse or cancel any order placed on the
          basis of such an error.
        </PolicyP>
      </PolicySection>

      <PolicySection num={3} title="User Information Requirement">
        <PolicyP>
          To place an order, you must provide accurate and complete details — including your name,
          delivery address, contact number and, if provided, an email address. You are responsible
          for the accuracy of this information and for informing us if any delivery detail changes
          before dispatch.
        </PolicyP>
      </PolicySection>

      <PolicySection num={4} title="Intellectual Property">
        <PolicyP>
          All content on this website — including graphics, artwork, product designs, logos, text,
          photography and layout — is the intellectual property of {POLICY_BUSINESS} or its
          licensors and is protected by applicable law. You may not reproduce, copy, republish or
          reuse any content without our prior written permission.
        </PolicyP>
      </PolicySection>

      <PolicySection num={5} title="Prohibited & Unlawful Use">
        <PolicyP>
          You agree not to use the website to violate any law, to upload or transmit harmful content,
          to interfere with the proper functioning of the website, or to attempt to obtain access to
          data that is not intended for you. Any such use may result in an order being cancelled and
          your access being revoked.
        </PolicyP>
      </PolicySection>

      <PolicySection num={6} title="Third-Party Links & Services">
        <PolicyP>
          The website may include links to third-party services such as payment gateways, courier
          tracking pages and social media. These are provided for your convenience. We do not control
          these third parties and are not responsible for their content, their privacy practices or
          the availability of their services. Your use of such third-party services is subject to
          their own terms.
        </PolicyP>
      </PolicySection>

      <PolicySection num={7} title="Transaction Terms">
        <PolicyP>Placing an order with {POLICY_BUSINESS} constitutes an offer to purchase the selected products.</PolicyP>
        <PolicyOl
          items={[
            'Prices are shown in Indian Rupees (INR) inclusive of applicable taxes unless stated otherwise. Shipping charges, if any, are shown at checkout.',
            'Orders are confirmed only when accepted by us. We may decline or cancel an order where stock is not available, payment is not successful, or a pricing or quantity error has occurred.',
            'Payment clears before the order is processed for dispatch. Order status and payment status are recorded on the order.',
            'We rely on selected sizes and colours specifically; product availability is subject to live stock. If any item in your order is unavailable, we will contact you before proceeding.',
          ]}
        />
      </PolicySection>

      <PolicySection num={8} title="Cancellations, Returns & Refunds">
        <PolicyP>
          Your cancellations, returns, exchanges and refunds are governed by our{' '}
          <a href="#/refund-and-cancellation" className="text-crimson underline hover:text-crimson-dark">
            Refund & Cancellation Policy
          </a>{' '}
          and our{' '}
          <a href="#/return-policy" className="text-crimson underline hover:text-crimson-dark">
            Return Policy
          </a>
          , which form part of these Terms.
        </PolicyP>
      </PolicySection>

      <PolicySection num={9} title="Shipping & Delivery">
        <PolicyP>
          Delivery is subject to our{' '}
          <a href="#/shipping-policy" className="text-crimson underline hover:text-crimson-dark">
            Shipping Policy
          </a>
          . Dispatch and delivery timelines, and courier-level delays outside our control, are
          addressed there and incorporated into these Terms.
        </PolicyP>
      </PolicySection>

      <PolicySection num={10} title="Indemnification">
        <PolicyP>
          You agree to indemnify and hold harmless {POLICY_BUSINESS}, its owners, employees and
          agents from any claims, losses, damages or expenses (including reasonable legal costs)
          arising out of your breach of these Terms, your misuse of the website, or any unlawful use
          of the products or services provided.
        </PolicyP>
      </PolicySection>

      <PolicySection num={11} title="Force Majeure">
        <PolicyP>
          We will not be liable for any delay or failure to perform our obligations under these Terms
          where such delay or failure is caused by events beyond our reasonable control — including,
          without limitation, natural disasters, government action, strikes, transport disruptions,
          courier delays or failures of third-party systems.
        </PolicyP>
      </PolicySection>

      <PolicySection num={12} title="Governing Law & Jurisdiction">
        <PolicyP>
          These Terms are governed by and construed in accordance with the laws of the Republic of
          India. Subject to the dispute provisions below, disputes arising out of or in connection
          with these Terms shall be subject to the jurisdiction of the courts in Tamil Nadu, India.
        </PolicyP>
      </PolicySection>

      <PolicySection num={13} title="Dispute Resolution">
        <PolicyP>
          If any dispute arises in connection with your order or these Terms, we will first attempt to
          resolve it amicably through good-faith discussion (for example, over WhatsApp or email).
          Should the dispute not be resolved amicably, you may seek recourse with the applicable
          consumer grievance authorities in India as per applicable law.
        </PolicyP>
      </PolicySection>

      <PolicySection num={14} title="Changes to These Terms">
        <PolicyP>
          We may update these Terms from time to time to reflect changes in our operations or legal
          requirements. The updated Terms will be posted on this page with a revised effective date.
          Continued use of the website or placement of orders after such changes constitutes your
          acceptance of the updated Terms.
        </PolicyP>
      </PolicySection>

      <PolicySection num={15} title="Contact Us">
        <PolicyP>
          Questions concerning these Terms may be directed to us through our{' '}
          <a href="#/contact" className="text-crimson underline hover:text-crimson-dark">Contact page</a>
          , on WhatsApp, or by email at hello.dslang@gmail.com.
        </PolicyP>
        <PolicyNote>
          {POLICY_ADDRESS}
        </PolicyNote>
      </PolicySection>
    </PolicyPageShell>
  );
}